### ISSUE TITLE
Create wireframe for website

### ISSUE THREAD

**Issue by Matteas-Eden** [Matteas-Eden/matteas-eden.github.io#2]
**User Story**
In order to create the initial layout and to get an idea of how different components may fit together, I would like to implement a simple wireframe. This wireframe will correlate to the final design, but will be devoid of almost all styling - simply white rectangles, or something similar in nature.

**Notes**
- Investigate material-ui Grid component
- Investigate creating layouts with CSS

**Comment by jacob-and-nathan** [comment]
Just to clarify, do you need to create a wireframe for a page that doesn't exist yet?
In which case, what are you going to put on the page?

**Comment by Matteas-Eden** [comment]
Firstly, this repository is only public for the sake of accommodating the requirements of GitHub pages - I don't expect, nor desire, others to comment on the issues I make here. They are purely for *personal use*.

Secondly, to address your questions; the wireframe will be the page in lieu of any real content and so, by design, would not have anything on it. The point is moot, however, as I've long since moved past this stage of development; I just haven't updated the issues on the repository.
